[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "AlgoSim_NodeGraphQt"
version = "0.0.0"
requires-python = "==3.11.*"
dependencies = [
  "Qt.py>=1.4.1",
]